FROM osrf/ros:humble-desktop-full

RUN apt-get update \
  && apt-get install -y \
  vim \
  git \
  ros-humble-spinnaker-camera-driver \
  && rm -rf /var/lib/apt/lists/*

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc


COPY /config/calibration.yml /root/.ros/camera_info/

CMD ["bash"]
